library(tm) 
library(textstem)
library(SnowballC)
library(readxl)
library(dplyr) 
library(wordcloud)

CorpusData<-Corpus(VectorSource(salarypred$FullDescription))
CorpusData<-tm_map(CorpusData,tolower) 
CorpusData <-tm_map(CorpusData, removeNumbers) 
CorpusData <- tm_map(CorpusData, stripWhitespace)
CorpusDataNew <- tm_map(CorpusData, content_transformer(gsub), pattern = "txt", replacement = "text", fixed=TRUE)
CorpusDataNew<-tm_map(CorpusDataNew,lemmatize_strings)
terms <-DocumentTermMatrix(CorpusData,control = list(weighting = function(x) weightTfIdf(x, normalize = FALSE)))
